
import type {Config} from 'tailwindcss';
import {fontFamily} from 'tailwindcss/defaultTheme';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      screens: {
        'xs': '475px',
      },
      fontFamily: {
        body: ['var(--font-pacifico)', 'Pacifico', 'cursive'],
        headline: ['var(--font-pacifico)', 'Pacifico', 'cursive'],
        code: ['monospace'],
        pacifico: ['var(--font-pacifico)', 'Pacifico', 'cursive'],
        display: ['var(--font-pacifico)', 'Pacifico', 'cursive'],
        raleway: ['var(--font-raleway)', 'Raleway', 'sans-serif'],
        editorial: ['var(--font-raleway)', 'Raleway', 'sans-serif'],
        jersey25: ['var(--font-jersey25)', 'Jersey 25', 'sans-serif'],
        brand: ['var(--font-jersey25)', 'Jersey 25', 'sans-serif'],
        'yrdly-display': ['var(--yrdly-font-display)', 'sans-serif'],
        'yrdly-body': ['var(--yrdly-font-body)', 'sans-serif'],
      },
      colors: {
        'surface-dim': 'var(--surface-dim)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'surface-bright': '#36393f',
        'surface-variant': '#32353a',
        'outline': '#899485',
        'outline-variant': '#40493d',
        'primary-fixed-dim': '#82db7e',
        'primary-container': '#4da24e',
        'on-primary-container': '#003207',
        'secondary-container': '#006ec9',
        'on-secondary-container': '#eaf0ff',
        'tertiary-container': '#35a61a',
        'tertiary': '#6edf51',
        'on-tertiary-container': '#053200',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        yrdly: {
          g: 'var(--yrdly-g)',
          glow: 'var(--yrdly-glow)',
          glowStrong: 'var(--yrdly-glow-strong)',
          dark: 'var(--yrdly-dark)',
          surfaceAlt: 'var(--yrdly-surface-alt)',
          glassBg: 'var(--yrdly-glass-bg)',
          glassBorder: 'var(--yrdly-glass-border)',
          surface: 'var(--yrdly-surface)',
          label: 'var(--yrdly-label)',
          muted: 'var(--yrdly-muted)',
          textPrimary: 'var(--yrdly-text-primary)',
          textSecondary: 'var(--yrdly-text-secondary)',
          gold: 'var(--yrdly-gold)',
          blue: 'var(--yrdly-blue)',
          amber: 'var(--yrdly-amber)',
          red: 'var(--yrdly-red)',
          danger: 'var(--yrdly-danger)',
          warning: 'var(--yrdly-warning)',
          divider: 'var(--yrdly-divider)',
          severityInfoBg: 'var(--yrdly-severity-info-bg)',
          severityInfoBorder: 'var(--yrdly-severity-info-border)',
          severityInfoText: 'var(--yrdly-severity-info-text)',
          severityInfoIcon: 'var(--yrdly-severity-info-icon)',
          severityCautionBg: 'var(--yrdly-severity-caution-bg)',
          severityCautionBorder: 'var(--yrdly-severity-caution-border)',
          severityCautionText: 'var(--yrdly-severity-caution-text)',
          severityCautionIcon: 'var(--yrdly-severity-caution-icon)',
          severityUrgentBg: 'var(--yrdly-severity-urgent-bg)',
          severityUrgentBorder: 'var(--yrdly-severity-urgent-border)',
          severityUrgentText: 'var(--yrdly-severity-urgent-text)',
          severityUrgentIcon: 'var(--yrdly-severity-urgent-icon)',
        },
      },
      spacing: {
        'yrdly-xs': '8px',
        'yrdly-sm': '12px',
        'yrdly-md': '16px',
        'yrdly-lg': '20px',
        'yrdly-xl': '24px',
        'yrdly-xxl': '32px',
        'yrdly-h40': '40px',
        'yrdly-h48': '48px',
        'yrdly-h64': '64px',
        'yrdly-h96': '96px',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'yrdly-card': '20px',
        'yrdly-modal': '24px',
        'yrdly-glassCard': '32px',
        'yrdly-input': '16px',
        'yrdly-button': '18px',
        'yrdly-chip': '20px',
        'yrdly-badge': '8px',
        'yrdly-iconBox': '12px',
        'yrdly-bottomSheet': '24px',
        'yrdly-avatar': '9999px',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
